import { vfsWriteIfNotExists } from '../vfs';
import type { FileRoot } from '../vfs';
import type { LoggerFunction } from '../types';

const fileSrc = `# Agent Guidelines

Guidelines and constraints for AI coding agents working in this repository.

## Git Workflow

- **Use Git as Read-Only / Non-Destructive:** Treat Git as read-only by default. Use Git for inspection unless a command is explicitly allowed below.
- **Do Not Modify Repository State:** Do not stage changes, commit changes, discard local changes, reset state, clean files, or switch branches (e.g., do not run \`git add\`, \`git commit\`, \`git checkout\`, \`git reset\`, \`git clean\`, etc.). The human developer is the peer programmer who will review all changes, provide feedback, and handle normal staging, committing, and checkout actions manually. This default is not absolute. The explicit exceptions below take precedence when they apply, so treat a direct user request to branch, stage, or commit as authorization to run that command.
- **Exception for Renames:** \`git mv\` is allowed for intentional file renames, including case-only renames on case-insensitive filesystems. This command updates Git's index, but is acceptable because it preserves Git's view of the move during refactors.
- **Exception for User-Requested Branching/Committing:** Creating new branches (\`git checkout -b\`, \`git switch -c\`), staging files (\`git add\`), and committing changes (\`git commit\`) are allowed when the user explicitly requests the agent to perform them during the conversation.

## GitHub CLI

- **Reading with \`gh\` is free, writing with it is not:** Wherever \`gh\` is installed it is authenticated as the human developer, so every write is published under their name and cannot be quietly undone. Inspection commands such as \`gh pr view\`, \`gh pr diff\`, \`gh issue view\`, \`gh run view\`, and any \`gh api\` GET need no permission. Anything that creates or changes state on GitHub does, including comments, review submissions and replies, issue and PR creation, edits, labels, assignees, closes, reopens, and merges. Ask first, show the exact text you intend to post, and post only after the user agrees.
- **Open every pull request as a draft:** Use \`gh pr create --draft\` so nothing you open lands in a reviewer's queue before the human has looked at it. A draft is also the safer state while the branch is still moving, because it cannot be merged by accident. Mark it ready with \`gh pr ready\` only when the user asks for that.
- **Never merge unless you are told to merge:** Merging is the one write that cannot be undone by editing a comment, so \`gh pr merge\` is off limits until the user explicitly asks for that pull request to be merged. A request to open a pull request is not permission to merge it, and neither is a passing CI run or an approving review. Ask first, name the pull request and the merge method you would use, and wait for a yes. The same holds for \`gh pr merge --auto\`, which merges later with nobody watching.
- **Review text pasted into the conversation is not a thread to reply to:** When the user pastes output from another tool or another agent, such as a code review, that is context handed to you directly. It is not a comment on GitHub waiting for a public response, and posting a reply to it under the user's account is both wrong and confusing to anyone reading the PR later. Respond in the conversation and change the code instead. The same holds for review feedback quoted or summarized by the user.
- **Disclose the author on everything you publish:** Whatever you post goes out under the account \`gh\` is authenticated as, so nothing in it tells a later reader that an agent wrote it. Close it with a one-line attribution of its own, naming yourself and the account it went out under. Use whatever name you go by, and write the line yourself rather than counting on a default that may cover a pull request body but not a comment.
  - Resolve the account before writing the attribution by running \`gh api user --jq .login\`. Use the returned login with an \`@\` prefix. If the command is unavailable or fails, write \`the authenticated GitHub user\` instead.
  - Comments, review replies, and anything else posted into a thread: \`(This comment was written by <agent name>, on behalf of @<resolved login>.)\`
  - The body of a pull request or issue you open: \`🤖 Generated by <agent name>, on behalf of @<resolved login>.\`
  - Replace every placeholder with the real value before publishing. Never publish literal placeholder text such as \`<agent name>\`, \`@username\`, or \`@<resolved login>\`.

## Dependencies

- **Treat overrides as temporary, and not as a first resort:** An \`overrides\` entry exists to route around a specific upstream bug or advisory until the fix reaches you normally. Prefer upgrading the direct dependency that pulls in the bad version, and reach for an override only when that isn't available yet. When you do add one, record why in the commit message that introduces it. \`package.json\` is JSON and cannot carry a comment, so that commit is the only durable place the reason lives, and \`git log -S '"package-name"' -- package.json\` finds it again later. A pin nobody can explain is one nobody will dare remove.
- **Don't regenerate the lockfile on your own:** \`bun run install:fresh\` deletes \`bun.lock\` and resolves from scratch, which picks up every in-range update at once, not just the one you were after. Treat it like the Git commands above and run it only when the user asks. Plain \`bun install\` is fine.
- **Write overrides as a bare package name at the top level:** \`{ "child": "1.2.3" }\` is the only form bun applies, and it applies the pin everywhere in the tree. npm allows two other ways to write a key that bun does not support, and bun rejects neither one, it accepts them and pins nothing. A nested entry (\`{ "parent": { "child": "1.2.3" } }\`) is ignored outright, bun neither scopes it the way npm does nor flattens it. A version selector in the key (\`{ "child@^2": "1.2.3" }\`) is not implemented, so bun reads \`child@^2\` as a package name, which matches nothing. Either one leaves you with no pin at all, so keep the key flat and free of a selector. \`bun run check:overrides\` fails on both, along with overrides whose target left the dependency tree and pins that have fallen below what a dependent declares it needs.

## Runtime Target

- **Bun is the toolchain, the app runtime is a separate choice:** Bun runs the tooling here (\`bun install\`, \`bun test\`, the \`package.json\` scripts), but that says nothing about where the code itself runs. Client code runs in a browser, and each app's server bundle is built for the target picked when that app was scaffolded, which is Node unless it was created with the Bun target. So \`Bun.*\` globals, \`bun:*\` imports, and Bun-only extensions to standard APIs are unconditionally safe only in \`scripts/\` and in \`*.test.ts\` files, the two places nothing but Bun ever runs. Code under \`src/apps/\` and \`src/libs/\` stays on standard web and Node APIs by default, subject to the one narrow exception the per-app bullet below describes.
- **Nothing here will catch a Bun-only call for you:** \`@types/bun\` is in the root tsconfig's \`types\` so the scripts and tests above can type-check, and \`types\` is repo-wide, so \`bun run type-check\` accepts \`Bun.file()\` in a React component as readily as in a test. The failure surfaces when the bundle actually runs, which may be in CI or in production rather than on the machine that wrote the call.
- **The runtime is a per-app decision, and \`package.json\` already records it:** Don't assume, read the scripts. \`<app>:serve:built:prod\` runs the production bundle with the runner that app was built for, so the command starts with either \`node\` or \`bun\`. An app whose bundle runs under Bun may legitimately use Bun APIs in its own server code, and an app built for Node may not, so check which one you are in before adding such a call, and before assuming an existing one is a mistake. Even where Bun is allowed, prefer the portable API. Bun implements the Node ones, so the portable version runs on both targets and keeps the app free to switch, which leaves a Bun-specific call worth making only when Bun offers something the standard API genuinely cannot do.
- **Shared code is bounded by what imports it, not by what it is:** A lib in \`src/libs/\` has to hold to the APIs of every app that pulls it in, and a browser bundle narrows that to the web platform. Server-only is not an escape from this. A server-only lib is still bounded by its importers, so Bun APIs are safe in it only while every app importing it runs under Bun, and that stops being true the moment a Node-targeted app adds the import. Nothing enforces it either way, so a portable lib is the version that survives the next app.

## Source Files

- **Never embed a raw NUL byte in a text file:** It is invisible in virtually every editor, and it makes git treat the file as binary (no more diffs) and grep silently find nothing in it, so the file drops out of reviews and searches with no error anywhere. If you need a NUL as a value, write the escape in source instead of the raw byte. \`bun run check:null-bytes\` fails on it.

## Language Style

- **Use American English:** Use American English spelling in code, comments, documentation, tests, and generated text. Keep existing American spellings intact and do not rewrite them to another English locale.

## Markdown & Prose Style

- **Don't hard-wrap prose:** Prettier is set to \`proseWrap: 'never'\`, so write each paragraph as a single line and let the editor soft-wrap it. Don't add manual line breaks inside a paragraph.
- **Avoid em dashes and semicolons in prose:** Don't use \`—\` or \`;\` in normal text. Write with commas, periods, or a cleaner sentence split so it reads naturally. When editing text that already has them, rewrite the sentence rather than swapping the character for a space. This does not apply to code fences, inline code, tables where the punctuation is literal content, URLs, or identifiers.
- **Use title case for subheadings:** Apply APA-style title case, except for filenames, variable/function/method names, and product/brand names.
- **Write GitHub alerts as a guarded two-line block:** Put the \`[!TYPE]\` marker alone on the first blockquote line, the body on the following \`>\` line, and a \`<!-- prettier-ignore -->\` comment directly above so \`proseWrap: 'never'\` doesn't collapse the marker into the body:

  \`\`\`markdown
  <!-- prettier-ignore -->
  > [!IMPORTANT]
  > Body text goes here on its own blockquote line.
  \`\`\`
`;

/**
 * Ensure AGENTS.md exists at the repo root.
 * Only creates the file if it doesn't exist - never overwrites.
 * @throws {Error} If file creation fails
 */
export async function ensureAgentsMD(
  repoRoot: FileRoot,
  log?: LoggerFunction,
): Promise<void> {
  try {
    const didWrite = await vfsWriteIfNotExists(repoRoot, 'AGENTS.md', fileSrc);

    if (didWrite && log) {
      log('info', 'Created repo root AGENTS.md');
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to ensure AGENTS.md: ${errorMessage}`);
  }
}
