/**
 * Sync version from package.json to src/version.ts
 * This ensures the package version is available throughout the codebase
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const projectRoot = join(import.meta.dir, '..');
const packageJsonPath = join(projectRoot, 'package.json');
const versionFilePath = join(projectRoot, 'src', 'version.ts');

try {
  // Read package.json
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8')) as {
    version?: string;
  };

  const version = packageJson.version;

  if (!version) {
    console.error('❌ No version found in package.json');
    process.exit(1);
  }

  // Generate version.ts content
  const versionFileContent = `/**
 * Auto-generated version file
 * DO NOT EDIT MANUALLY - This file is generated by scripts/sync-version.ts
 * Run 'bun run sync-version' to update
 */

export const PKG_VERSION = '${version}';
`;

  // Write version.ts
  writeFileSync(versionFilePath, versionFileContent, 'utf-8');

  console.log(`✅ Synced version ${version} to src/version.ts`);
} catch (error) {
  console.error('❌ Failed to sync version:', error);
  process.exit(1);
}
